name: cxr

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - pandas
  - matplotlib
  - h5py

  - pip:
      - pydicom
      - opencv-python
      - torch
      - torchvision
      - pytorch-lightning
      - timm
      - monai
      - streamlit
      - mlflow
      - dvc
      - dvc[gdrive]
      - pydantic
      - reportlab
      - pytest
      - pytest-cov
      - scikit-learn
      - tqdm